# Default values for spark.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ENV: local

replicaCount: 1
spark_driver:
  mode: client
  local_checkpoint:
    enabled: false
    size: 1Gi
  image:
    repository: ci-dcr.flix.tech/data/flux/cujo-raw-to-master-spark
    tag: to_be_overwrite
    pullPolicy: IfNotPresent
  env:
    PY_FILES: /workspace/dist/libs.zip,/workspace/dist/dependencies.zip
  container:
    command: []
    args: []
  resources:
    limits:
      memory: 524Mi
    requests:
      memory: 524Mi
  iamRoleArn: arn:aws:iam::xxxxxx:role/xxxxx

spark_properties: |-
  spark.executor.instances=1
  spark.kubernetes.namespace=default
  spark.kubernetes.allocation.batch.size=5
  spark.kubernetes.allocation.batch.delay=1s
  spark.kubernetes.authenticate.driver.serviceAccountName=spark
  spark.kubernetes.executor.lostCheck.maxAttempts=10
  spark.kubernetes.submission.waitAppCompletion=false
  spark.kubernetes.report.interval=1s
  spark.kubernetes.pyspark.pythonVersion=3

  #kubernetes resource managements
  spark.kubernetes.driver.request.cores=10m
  spark.kubernetes.executor.request.cores=50m
  spark.executor.memory=500m
  spark.kubernetes.memoryOverheadFactor=0.1

  spark.kubernetes.executor.annotation.cluster-autoscaler.kubernetes.io/safe-to-evict=true
  spark.sql.streaming.metricsEnabled=true

serviceAccount:
  create: false
  name: spark

service:
  type: ClusterIP

datadog:
  enabled: true
