apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "spark-driver.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/change-cause: "{{ .Values.spark_driver.image.repository }}:{{ .Values.spark_driver.image.tag }}"
    downscaler/uptime: always
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "spark-driver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "spark-driver.selectorLabels" . | nindent 8 }}
    {{- if .Values.datadog.enabled }}
      annotations:
        iam.amazonaws.com/role: {{ .Values.spark_driver.iamRoleArn }}
        ad.datadoghq.com/{{ .Release.Name }}.logs: '{{ toJson (fromYaml (tpl (.Files.Get "monitoring/custom_metrics.yaml") .)).logs }}'
        # label for existing template on file
        ad.datadoghq.com/{{ .Release.Name }}.check_names: '["spark"]'  # becomes instance tag in datadog
        ad.datadoghq.com/{{ .Release.Name }}.init_configs: '[{{ toJson (fromYaml (tpl (.Files.Get "monitoring/custom_metrics.yaml") .)).init_config }}]'
        ad.datadoghq.com/{{ .Release.Name }}.instances: '{{ toJson (fromYaml (tpl (.Files.Get "monitoring/custom_metrics.yaml") .)).instances }}'
    {{- end }}
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/spot"
        operator: "Exists"
      serviceAccountName: {{ include "spark-driver.serviceAccountName" . }}
      volumes:
      - name: "{{ .Release.Name }}-configmap"
        configMap:
          name: "{{ .Release.Name }}-configmap"
      {{- if .Values.spark_driver.local_checkpoint.enabled }}
      - name: "{{ .Release.Name }}-checkpoint"
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-checkpoint"
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.spark_driver.image.repository }}:{{ .Values.spark_driver.image.tag }}
          imagePullPolicy: {{ .Values.spark_driver.image.pullPolicy }}
          command:
            {{- range .Values.spark_driver.container.command }}
            - {{ .}}
            {{- end }}
          args:
            {{- range .Values.spark_driver.container.args }}
            - {{ .}}
            {{- end }}
          env:
            {{- range $key, $value := .Values.spark_driver.env }}
            - name: {{ $key | quote }}
              value: {{ tpl $value $ | quote }}
            {{- end }}
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SERVICE_NAME
              value: {{ .Release.Name }}
            - name: CONTAINER_IMAGE
              value: {{ .Values.spark_driver.image.repository }}:{{ .Values.spark_driver.image.tag }}
            - name: SPARK_MODE
              value: {{ .Values.spark_driver.mode | quote }}
          volumeMounts:
          - name: "{{ .Release.Name }}-configmap"
            mountPath: "/opt/spark.properties"
            subPath: "spark.properties"
          {{- if .Values.spark_driver.local_checkpoint.enabled }}
          - name: "{{ .Release.Name }}-checkpoint"
            mountPath: {{ .Values.spark_driver.env.CHECKPOINT_LOCATION}}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: driver-rpc-port
              containerPort: 7078
              protocol: TCP
            - name: blockmanager
              containerPort: 7079
              protocol: TCP
            - name: spark-ui
              containerPort: 4040
              protocol: TCP
          resources:
            {{- toYaml .Values.spark_driver.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
